### ISSUE TITLE
sansa-query-spark depends on sparkbench

### ISSUE THREAD

**Issue by GiorgosMandi** [SANSA-Stack/SANSA-Stack#127]
Hello, 

I am using SANSA-Stack to load an NTRIPLES file, which I want to query.  So, my code looks like this 

```scala
    import net.sansa_stack.query.spark.query._
    import net.sansa_stack.rdf.spark.io._
    import net.sansa_stack.rdf.spark.model._
    
    val input = "/path/to/file.nt"
    val lang = Lang.NTRIPLES
    val triples = spark.rdf(lang)(input)
     
    val sparqlQuery = "SELECT * WHERE {?s ?p ?o} LIMIT 10"
    val result = triples.sparql(sparqlQuery)
```
But I'm having issues installing the sbt dependency **"net.sansa-stack" %% "sansa-query-spark" % "0.7.1"** 
In more details, my **build.sbt** looks like this:
```scala
    scalaVersion := "2.11.12"
    val sparkVersion = "2.4.4"
    
    resolvers += "AKSW Maven Snapshots" at "https://maven.aksw.org/archiva/repository/snapshots"
    resolvers += "jitpack" at "https://jitpack.io"
    
    libraryDependencies ++= Seq(
	    "org.apache.spark" %%  "spark-core" % sparkVersion % Provided,
	    "org.apache.spark" %%  "spark-sql" % sparkVersion  % Provided,
    )
    
    // https://mvnrepository.com/artifact/net.sansa-stack/sansa-rdf-spark
    libraryDependencies += "net.sansa-stack" %% "sansa-rdf-spark" % "0.7.1"
    
    // https://mvnrepository.com/artifact/net.sansa-stack/sansa-query-spark
    libraryDependencies += "net.sansa-stack" %% "sansa-query-spark" % "0.7.1"
```

and I get the following error:

    [warn]  Note: Unresolved dependencies path:
    [error] sbt.librarymanagement.ResolveException: Error downloading com.ibm.sparktc.sparkbench:sparkbench:2.3.0_0.4.0
    [error]   Not found
    [error]   Not found
    [error]   not found: /home/gmandi/.ivy2/local/com.ibm.sparktc.sparkbench/sparkbench/2.3.0_0.4.0/ivys/ivy.xml
    [error]   not found: https://repo1.maven.org/maven2/com/ibm/sparktc/sparkbench/sparkbench/2.3.0_0.4.0/sparkbench-2.3.0_0.4.0.pom
    [error]   not found: https://maven.aksw.org/archiva/repository/snapshots/com/ibm/sparktc/sparkbench/sparkbench/2.3.0_0.4.0/sparkbench-2.3.0_0.4.0.pom
    [error]   not found: https://jitpack.io/com/ibm/sparktc/sparkbench/sparkbench/2.3.0_0.4.0/sparkbench-2.3.0_0.4.0.pom
    [error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:247)
    [error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:216)
    [error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
    [error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:216)
    [error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
    [error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
    [error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
    [error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
    [error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
    [error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
    [error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
    [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
    [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
    [error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
    [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
    [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
    [error]         at sbt.Execute.work(Execute.scala:290)
    [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
    [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
    [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
    [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    [error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    [error]         at java.lang.Thread.run(Thread.java:748)
    [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.ibm.sparktc.sparkbench:sparkbench:2.3.0_0.4.0
    [error]   Not found
    [error]   Not found
    [error]   not found: /home/gmandi/.ivy2/local/com.ibm.sparktc.sparkbench/sparkbench/2.3.0_0.4.0/ivys/ivy.xml
    [error]   not found: https://repo1.maven.org/maven2/com/ibm/sparktc/sparkbench/sparkbench/2.3.0_0.4.0/sparkbench-2.3.0_0.4.0.pom
    [error]   not found: https://maven.aksw.org/archiva/repository/snapshots/com/ibm/sparktc/sparkbench/sparkbench/2.3.0_0.4.0/sparkbench-2.3.0_0.4.0.pom
    [error]   not found: https://jitpack.io/com/ibm/sparktc/sparkbench/sparkbench/2.3.0_0.4.0/sparkbench-2.3.0_0.4.0.pom

Do you know where is the repository of the **sparkbench** dependency, or if there is a workaround on this issue?

Thanks in advance.

**Comment by GiorgosMandi** [comment]
I excluded it and it worked
