### ISSUE TITLE
Handling Bad Triples

### ISSUE THREAD

**Issue by carstendraschner** [SANSA-Stack/SANSA-Stack#135]
I want to play around with lmdb data for the development of fitting ml pipelines
data can be found here:

http://www.cs.toronto.edu/~oktie/linkedmdb/linkedmdb-18-05-2009-dump.nt

the current implementation of the pipeline can be found here:

https://github.com/SANSA-Stack/SANSA-Stack/blob/use_case/eauc_sansa_api/sansa-examples/sansa-examples-spark/src/main/scala/net/sansa_stack/examples/spark/ml/LMDB_Pipeline.scala

I guess it is coming from triples like this: `<http://data.linkedmdb.org/resource/interlink/121646> <http://data.linkedmdb.org/resource/oddlinker/link_target> <http://www4.wiwiss.fu-berlin.de/bookmashup/persons/Edwin%2B"Bud"%2BShrake> .`

I tried to not use the common way (spark.read) of reading in to be capable to skip bad triples. That's why I searched and found maybe this option

```
val dataset = NTripleReader.load(
      spark,
      inputFilePath,
      stopOnBadTerm = ErrorParseMode.SKIP,
      stopOnWarnings = WarningParseMode.SKIP
    ).toDS().cache()
```

by using this, I can read in but as soon as I want to query on this data I get following stack trace:

```
21/02/16 12:23:59 ERROR riot: [line: 1, col: 39] Bad character in IRI (space): <http://www.freebase.com/viewOrgasmic[space]...>
21/02/16 12:23:59 ERROR Executor: Exception in task 21.0 in stage 4.0 (TID 51)
org.apache.jena.riot.RiotException: [line: 1, col: 39] Bad character in IRI (space): <http://www.freebase.com/viewOrgasmic[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:146)
	at org.apache.jena.riot.tokens.TokenizerText.error(TokenizerText.java:1287)
	at org.apache.jena.riot.tokens.TokenizerText.readIRI(TokenizerText.java:505)
	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:197)
	at org.apache.jena.riot.tokens.TokenizerText.hasNext(TokenizerText.java:89)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.parse(JenaKryoSerializers.scala:65)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.read(JenaKryoSerializers.scala:56)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.read(JenaKryoSerializers.scala:31)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$TripleSerializer.read(JenaKryoSerializers.scala:235)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$TripleSerializer.read(JenaKryoSerializers.scala:225)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at org.apache.spark.serializer.KryoSerializerInstance.deserialize(KryoSerializer.scala:397)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$1560/000000000000000000.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
21/02/16 12:23:59 ERROR TaskSetManager: Task 21 in stage 4.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 21 in stage 4.0 failed 1 times, most recent failure: Lost task 21.0 in stage 4.0 (TID 51, carstens-mbp-16, executor driver): org.apache.jena.riot.RiotException: [line: 1, col: 39] Bad character in IRI (space): <http://www.freebase.com/viewOrgasmic[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:146)
	at org.apache.jena.riot.tokens.TokenizerText.error(TokenizerText.java:1287)
	at org.apache.jena.riot.tokens.TokenizerText.readIRI(TokenizerText.java:505)
	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:197)
	at org.apache.jena.riot.tokens.TokenizerText.hasNext(TokenizerText.java:89)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.parse(JenaKryoSerializers.scala:65)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.read(JenaKryoSerializers.scala:56)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.read(JenaKryoSerializers.scala:31)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$TripleSerializer.read(JenaKryoSerializers.scala:235)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$TripleSerializer.read(JenaKryoSerializers.scala:225)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at org.apache.spark.serializer.KryoSerializerInstance.deserialize(KryoSerializer.scala:397)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$1560/000000000000000000.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2008)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2007)
	at org.apache.spark.scheduler.DAGScheduler$$Lambda$2950/0x00000000ed074e20.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2007)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:973)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:973)
	at org.apache.spark.scheduler.DAGScheduler$$Lambda$2947/0x00000000ed07dc20.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:973)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2239)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2188)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2177)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:775)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2120)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2139)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2164)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
	at org.apache.spark.rdd.RDD$$Lambda$1680/0x00000000e935da20.apply(Unknown Source)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
	at net.sansa_stack.rdf.spark.partition.core.RdfPartitionUtilsSpark$.partitionGraphArray(RdfPartitionUtilsSpark.scala:26)
	at net.sansa_stack.rdf.spark.partition.core.RdfPartitionUtilsSpark$.partitionGraph(RdfPartitionUtilsSpark.scala:19)
	at net.sansa_stack.rdf.spark.partition.package$RDFPartition.verticalPartition(package.scala:48)
	at net.sansa_stack.ml.spark.featureExtraction.SparqlFrame.transform(SparqlFrame.scala:117)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline$.main(LMDB_Pipeline.scala:102)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline.main(LMDB_Pipeline.scala)
Caused by: org.apache.jena.riot.RiotException: [line: 1, col: 39] Bad character in IRI (space): <http://www.freebase.com/viewOrgasmic[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:146)
	at org.apache.jena.riot.tokens.TokenizerText.error(TokenizerText.java:1287)
	at org.apache.jena.riot.tokens.TokenizerText.readIRI(TokenizerText.java:505)
	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:197)
	at org.apache.jena.riot.tokens.TokenizerText.hasNext(TokenizerText.java:89)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.parse(JenaKryoSerializers.scala:65)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.read(JenaKryoSerializers.scala:56)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$NodeSerializer.read(JenaKryoSerializers.scala:31)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$TripleSerializer.read(JenaKryoSerializers.scala:235)
	at net.sansa_stack.rdf.common.kryo.jena.JenaKryoSerializers$TripleSerializer.read(JenaKryoSerializers.scala:225)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at org.apache.spark.serializer.KryoSerializerInstance.deserialize(KryoSerializer.scala:397)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$1560/000000000000000000.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
21/02/16 12:23:59 ERROR TaskSchedulerImpl: Exception in statusUpdate
java.util.concurrent.RejectedExecutionException: Task org.apache.spark.scheduler.TaskResultGetter$$Lambda$2940/0x00000000e9445e20@78d5b338 rejected from java.util.concurrent.ThreadPoolExecutor@d605ed0a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 52]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at org.apache.spark.scheduler.TaskResultGetter.enqueueFailedTask(TaskResultGetter.scala:137)
	at org.apache.spark.scheduler.TaskSchedulerImpl.liftedTree2$1(TaskSchedulerImpl.scala:624)
	at org.apache.spark.scheduler.TaskSchedulerImpl.statusUpdate(TaskSchedulerImpl.scala:599)
	at org.apache.spark.scheduler.local.LocalEndpoint$$anonfun$receive$1.applyOrElse(LocalSchedulerBackend.scala:71)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox$$Lambda$206/000000000000000000.apply$mcV$sp(Unknown Source)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:203)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
21/02/16 12:23:59 ERROR Utils: Uncaught exception in thread Executor task launch worker for task 49
java.lang.NullPointerException
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:148)
	at org.apache.spark.scheduler.Task$$Lambda$1649/000000000000000000.apply$mcV$sp(Unknown Source)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1357)
	at org.apache.spark.scheduler.Task.run(Task.scala:146)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$1560/000000000000000000.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)


```

**Comment by Aklakan** [comment]
I changed node serialization to use thrift by default now; this protocol should not care about invalid rdf terms and write/read them as given. Tests are currently running...

**Comment by Aklakan** [comment]
Tests are now succeeding;
@carstendraschner i merged the code into develop; you can rebuild and try whether this solves your issues

**Comment by Aklakan** [comment]
Based on recent feedback in the skype channel it seems the serialization is now working as @carstendraschner 's use case now hits #129 again (which implies that query execution and result set analysis as preprocessing for schema mapping have completed successfully)

**Comment by Aklakan** [comment]
@carstendraschner is this issue solved with the new node serialization?

**Comment by Aklakan** [comment]
Closing this because internal serialization no longer cares about validity. There is a related issue that Ontop does not allow inconsistent ontologies but this is nothing we can adress atm.
