### ISSUE TITLE
ml-spark tests: ClassNotFoundException: it.unibz.inf.ontop.com.google.common.collect.NaturalOrderinç [sic!]

### ISSUE THREAD

**Issue by Aklakan** [SANSA-Stack/SANSA-Stack#150]
running mvn clean install on the develop branch raised the exception below.
It may be due to a typo in the source code (unlikely), a bug in the use of kryo or an incorrect use of encoding (maybe a missing StandardCharsets.UTF8 argument to input/output streams?)

```
com.esotericsoftware.kryo.KryoException: Unable to find class: it.unibz.inf.ontop.com.google.common.collect.NaturalOrderinç-
Serialization trace:
sqlSignature (net.sansa_stack.query.spark.ontop.RewriteInstruction)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804)
	at net.sansa_stack.query.spark.ontop.kryo.ShadedImmutableSortedSetSerializer.read(ShadedImmutableSortedSetSerializer.java:34)
	at net.sansa_stack.query.spark.ontop.kryo.ShadedImmutableSortedSetSerializer.read(ShadedImmutableSortedSetSerializer.java:13)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at net.sansa_stack.query.spark.ontop.KryoUtils$.deserialize(KryoUtils.scala:113)
	at net.sansa_stack.query.spark.ontop.OntopRowMapper.<init>(OntopRowMapper.scala:49)
	at net.sansa_stack.query.spark.ontop.QueryEngineOntop.$anonfun$computeBindings$1(QueryEngineOntop.scala:305)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:195)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.sql.execution.SQLExecutionRDD.compute(SQLExecutionRDD.scala:55)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: it.unibz.inf.ontop.com.google.common.collect.NaturalOrderinç-
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
	... 44 more
21/03/06 19:34:26 ERROR TaskSetManager: Task 0 in stage 48.0 failed 1 times; aborting job
- Results of a SPARQL query with four projection variables should be correct *** FAILED ***
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 48.0 failed 1 times, most recent failure: Lost task 0.0 in stage 48.0 (TID 2194, 192.168.1.37, executor driver): com.esotericsoftware.kryo.KryoException: Unable to find class: it.unibz.inf.ontop.com.google.common.collect.NaturalOrderinç-
Serialization trace:
sqlSignature (net.sansa_stack.query.spark.ontop.RewriteInstruction)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804)
	at net.sansa_stack.query.spark.ontop.kryo.ShadedImmutableSortedSetSerializer.read(ShadedImmutableSortedSetSerializer.java:34)
	at net.sansa_stack.query.spark.ontop.kryo.ShadedImmutableSortedSetSerializer.read(ShadedImmutableSortedSetSerializer.java:13)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at net.sansa_stack.query.spark.ontop.KryoUtils$.deserialize(KryoUtils.scala:113)
	at net.sansa_stack.query.spark.ontop.OntopRowMapper.<init>(OntopRowMapper.scala:49)
	at net.sansa_stack.query.spark.ontop.QueryEngineOntop.$anonfun$computeBindings$1(QueryEngineOntop.scala:305)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:195)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.sql.execution.SQLExecutionRDD.compute(SQLExecutionRDD.scala:55)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: it.unibz.inf.ontop.com.google.common.collect.NaturalOrderinç-
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
	... 44 more

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2059)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2008)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2007)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2007)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:973)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:973)
  at scala.Option.foreach(Option.scala:407)
  ...
  Cause: com.esotericsoftware.kryo.KryoException: Unable to find class: it.unibz.inf.ontop.com.google.common.collect.NaturalOrderinç-
Serialization trace:
sqlSignature (net.sansa_stack.query.spark.ontop.RewriteInstruction)
  at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
  at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
  at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
  at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804)
  at net.sansa_stack.query.spark.ontop.kryo.ShadedImmutableSortedSetSerializer.read(ShadedImmutableSortedSetSerializer.java:34)
  at net.sansa_stack.query.spark.ontop.kryo.ShadedImmutableSortedSetSerializer.read(ShadedImmutableSortedSetSerializer.java:13)
  at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
  at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
  at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
  ...
  Cause: java.lang.ClassNotFoundException: it.unibz.inf.ontop.com.google.common.collect.NaturalOrderinç-
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
  at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
  at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
  at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804)
  at net.sansa_stack.query.spark.ontop.kryo.ShadedImmutableSortedSetSerializer.read(ShadedImmutableSortedSetSerializer.java:34)
  ...

**Comment by carstendraschner** [comment]
after you @Aklakan recent commit I face following issue:
Exception in thread "main" java.lang.RuntimeException: Error processing sqlOp SqlOpTable [tableName="rdd-1563471318_httpp3ap2fp2fdataclinkedmdbcorgp2fmoviep2fdubbing_performance_name_xmlschemap23string_lang", aliasName=null], reason: Column "o" does not exist.
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.createMinimalSchema(EffectiveViewGenerator.java:165)
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.createQuadMaps(EffectiveViewGenerator.java:141)
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.transform(EffectiveViewGenerator.java:185)
	at org.aksw.sparqlify.config.v0_2.bridge.ConfiguratorCandidateSelector.configure(ConfiguratorCandidateSelector.java:33)
	at org.aksw.sparqlify.util.SparqlifyUtils.createDefaultSparqlSqlStringRewriter(SparqlifyUtils.java:501)
	at net.sansa_stack.query.spark.sparqlify.SparqlifyUtils3$.createSparqlSqlRewriter(SparqlifyUtils3.scala:64)
	at net.sansa_stack.query.spark.sparqlify.QueryEngineFactorySparqlify.create(QueryEngineFactorySparqlify.scala:13)
	at net.sansa_stack.query.spark.package$SPARQLEnginePrePartitionedImplicit.sparql(package.scala:81)
	at net.sansa_stack.query.spark.package$SPARQLEnginePrePartitionedImplicit.sparqlify(package.scala:85)
	at net.sansa_stack.ml.spark.featureExtraction.SparqlFrame.transform(SparqlFrame.scala:78)
	at net.sansa_stack.ml.spark.featureExtraction.FeatureExtractingSparqlGenerator$.createSparql(FeatureExtractingSparqlGenerator.scala:264)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline$.main(LMDB_Pipeline.scala:73)
	at net.sansa_stack.examples.spark.ml.LMDB_Pipeline.main(LMDB_Pipeline.scala)
Caused by: java.lang.RuntimeException: Column "o" does not exist.
	at org.aksw.sparqlify.core.sql.schema.SchemaImpl.createSubSchema(SchemaImpl.java:180)
	at org.aksw.sparqlify.core.cast.EffectiveViewGenerator.createMinimalSchema(EffectiveViewGenerator.java:163)
	... 12 more

**Comment by Aklakan** [comment]
Both issues fixed with all the recent updates.
