### ISSUE TITLE
Error reading RDF file

### ISSUE THREAD

**Issue by mileswhen** [SANSA-Stack/SANSA-Stack#162]
Hi,

Thanks for releasing a 0.8! I'm getting an error running the following code in a Zeppelin notebook, would be great to get some help!

```scala
import net.sansa_stack.rdf.spark.io._
import org.apache.jena.riot.Lang

// read rdf into rdd of triples
val inputpath = "file:///path/to/ontology.owl"
val lang = Lang.RDFXML
val triples = spark.rdf(lang)(inputpath)
```

Error message:
```
java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/snappy/SnappyCompressorInputStream
  at org.apache.jena.riot.RDFLanguages.pathnameToLang(RDFLanguages.java:423)
  at org.apache.jena.riot.RDFLanguages.guessContentType(RDFLanguages.java:456)
  at org.apache.jena.riot.system.stream.LocatorClassLoader.open(LocatorClassLoader.java:73)
  at org.apache.jena.riot.system.stream.StreamManager.openNoMapOrNull(StreamManager.java:176)
  at org.apache.jena.riot.RDFParser.openTypedInputStream(RDFParser.java:392)
  at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:302)
  at org.apache.jena.riot.RDFParser.parse(RDFParser.java:296)
  at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:540)
  at org.apache.jena.riot.RDFDataMgr.parseFromURI(RDFDataMgr.java:921)
  at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:252)
  at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:133)
  at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:124)
  at org.apache.jena.riot.RDFDataMgr.loadModel(RDFDataMgr.java:366)
  at org.aksw.jena_sparql_api.common.DefaultPrefixes.<clinit>(DefaultPrefixes.java:36)
  at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.registerResourceClasses(JenaPluginUtils.java:179)
  at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.registerResourceClasses(JenaPluginUtils.java:174)
  at org.aksw.r2rml.jena.plugin.JenaPluginR2rml.init(JenaPluginR2rml.java:38)
  at org.aksw.r2rml.jena.plugin.JenaPluginR2rml.start(JenaPluginR2rml.java:28)
  at org.apache.jena.sys.JenaSystem.lambda$init$2(JenaSystem.java:117)
  at java.util.ArrayList.forEach(ArrayList.java:1259)
  at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:192)
  at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:169)
  at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:115)
  at org.apache.jena.graph.NodeFactory.<clinit>(NodeFactory.java:32)
  at org.apache.jena.rdf.model.impl.ResourceImpl.fresh(ResourceImpl.java:141)
  at org.apache.jena.rdf.model.impl.ResourceImpl.<init>(ResourceImpl.java:87)
  at org.apache.jena.rdf.model.ResourceFactory$Impl.createResource(ResourceFactory.java:313)
  at org.apache.jena.rdf.model.ResourceFactory.createResource(ResourceFactory.java:92)
  at org.apache.jena.vocabulary.RDFS.resource(RDFS.java:35)
  at org.apache.jena.vocabulary.RDFS$Init.Class(RDFS.java:68)
  at org.apache.jena.vocabulary.RDFS.<clinit>(RDFS.java:40)
  at org.apache.jena.shared.PrefixMapping.<clinit>(PrefixMapping.java:219)
  at org.apache.jena.shared.PrefixMapping$Factory.create(PrefixMapping.java:212)
  at net.sansa_stack.rdf.spark.io.package$.<init>(package.scala:70)
  at net.sansa_stack.rdf.spark.io.package$.<clinit>(package.scala)
  ... 45 elided
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.snappy.SnappyCompressorInputStream
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 80 more
```

This is with the "sansa-examples-spark_2.11-0.8.0-RC1-backport-jar-with-dependencies.jar" + Spark 2.3.1, Hadoop 2.7, Zeppelin 0.9, and Scala 2.11.

**Comment by mileswhen** [comment]
Tried the spark_2.12 JAR with Spark 3.x and didn't encounter this error
