### ISSUE TITLE
A problem of RDF data reading

### ISSUE THREAD

**Issue by ishixiaoyi** [SANSA-Stack/SANSA-Stack#167]
Dear team

I tried to run some code which based the sample code "DistRDF2ML_Clustering.scala" but found some NotSerializableExceptionerror  occurred as below.

org.apache.spark.SparkException: Task not serializable                          
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:416)
  at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:406)
  at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
  at org.apache.spark.SparkContext.clean(SparkContext.scala:2377)
  at org.apache.spark.rdd.RDD.$anonfun$map$1(RDD.scala:396)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
  at org.apache.spark.rdd.RDD.map(RDD.scala:395)
  at org.apache.spark.api.java.JavaRDDLike.map(JavaRDDLike.scala:93)
  at org.apache.spark.api.java.JavaRDDLike.map$(JavaRDDLike.scala:92)
  at org.apache.spark.api.java.AbstractJavaRDDLike.map(JavaRDDLike.scala:45)
  at net.sansa_stack.query.spark.sparqlify.QueryExecutionUtilsSpark.createQueryExecution(QueryExecutionUtilsSpark.java:45)
  at net.sansa_stack.query.spark.sparqlify.JavaQueryExecutionSparkSparqlify.execSelectSparkJava(JavaQueryExecutionSparkSparqlify.java:31)
  at net.sansa_stack.query.spark.api.impl.QueryExecutionSparkJavaWrapper.execSelectSpark(QueryExecutionSparkJavaWrapper.scala:19)
  at net.sansa_stack.ml.spark.featureExtraction.SparqlFrame.transform(SparqlFrame.scala:254)
  ... 47 elided
Caused by: java.io.NotSerializableException: org.aksw.jena_sparql_api.views.RestrictedExpr
Serialization stack:
	- object not serializable (class: org.aksw.jena_sparql_api.views.RestrictedExpr, value: RestrictedExpr [expr=(http://aksw.org/sparqlify/rdfTerm 1 ?C_2 "" ""), restrictions=true])
	- writeObject data (class: net.sansa_stack.ext.com.google.common.collect.HashMultimap)
	- object (class net.sansa_stack.ext.com.google.common.collect.HashMultimap, {?s=[RestrictedExpr [expr=(http://aksw.org/sparqlify/rdfTerm 1 ?C_2 "" ""), restrictions=true]], ?p=[RestrictedExpr [expr=(http://aksw.org/sparqlify/rdfTerm 1.0 ?C_4 "" ""), restrictions=true]], ?o=[RestrictedExpr [expr=(http://aksw.org/sparqlify/rdfTerm 2 ?C_5 "" ""), restrictions=true], RestrictedExpr [expr=(http://aksw.org/sparqlify/rdfTerm 1 ?C_6 "" ""), restrictions=true], RestrictedExpr [expr=(http://aksw.org/sparqlify/rdfTerm 3 ?C_7 "" <http://www.w3.org/2001/XMLSchema#DateTime>), restrictions=true]]})
	- field (class: net.sansa_stack.query.spark.sparqlify.SparkRowMapperSparqlify, name: varDef, type: interface net.sansa_stack.ext.com.google.common.collect.Multimap)
	- object (class net.sansa_stack.query.spark.sparqlify.SparkRowMapperSparqlify, net.sansa_stack.query.spark.sparqlify.SparkRowMapperSparqlify@115594b8)
Serialization stack:

Does anyone could let me know if you met this error or not before?

The SQL string is as below
val sparqlString = "SELECT ?s ?p ?o WHERE {?s ?p ?o .}"

Attached the ttl file(zipped)
[SpeckledBand.ttl.zip](https://github.com/SANSA-Stack/SANSA-Stack/files/7110829/SpeckledBand.ttl.zip)

**Comment by Aklakan** [comment]
Hi, can you check whether you have the kryo registrators added as described in the [sansa-query-spark readme](https://github.com/SANSA-Stack/SANSA-Stack/tree/develop/sansa-query#from-file)

```scala
val spark = SparkSession.builder
        .appName(s"SPARQL engine example")
        .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") // we need Kryo serialization enabled with some custom serializers
        .config("spark.kryo.registrator", String.join(
          ", ",
          "net.sansa_stack.rdf.spark.io.JenaKryoRegistrator",
          "net.sansa_stack.query.spark.ontop.OntopKryoRegistrator",
          "net.sansa_stack.query.spark.sparqlify.KryoRegistratorSparqlify"))
        .config("spark.sql.crossJoin.enabled", true) // needs to be enabled if your SPARQL query does make use of cartesian product Note: in Spark 3.x it's enabled by default
        .getOrCreate()

```

The offending non-serializable class actually has a [registration](https://github.com/SANSA-Stack/SANSA-Stack/blob/develop/sansa-query/sansa-query-spark/src/main/java/net/sansa_stack/query/spark/sparqlify/KryoRegistratorSparqlify.java) there.

**Comment by ishixiaoyi** [comment]
Hi @Aklakan 
Thanks for your support and sorry for my late response.

Team master tried again in 2 different environments and found although your solution failed in spark shell but works well as the jar submit method. 

So we suppose might we meet the issue of spark shell but not the serializer class.

Thanks for your support again and let me close this ticket.
Xiaoyi
