### ISSUE TITLE
[ExceptionInInitializerError] Jackson Databind version >= 2.10.0 and < 2.11.0

### ISSUE THREAD

**Issue by ofilangi** [SANSA-Stack/SANSA-Stack#169]
I'm trying to run the example [TripleReader](https://github.com/SANSA-Stack/Archived-SANSA-Examples/blob/master/sansa-examples-spark/src/main/scala/net/sansa_stack/examples/spark/rdf/TripleReader.scala) on a spark cluster

I get the following error `Scala module 2.10.4 requires Jackson Databind version >= 2.10.0 and < 2.11.0` despite the definition in my config build.sbt targetting the 2.10.5 version.

### build.sbt 
```sbt
import Dependencies._

ThisBuild / scalaVersion     := "2.12.10"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

val sansaVersion = "0.8.0-RC2-SNAPSHOT"
val sparkVersion = "3.1.2"

lazy val root = (project in file("."))
  .settings(
    name := "sansa-test",
      libraryDependencies ++= Seq(
		  scalaTest % Test,
		  "javax.servlet" % "servlet-api" % "2.5",
		  "org.slf4j" % "slf4j-api" % "2.0.0-alpha5",
		  "com.fasterxml.jackson.core" % "jackson-databind" % "2.10.5",
		  "org.apache.zookeeper" % "zookeeper" % "3.7.0",
		  "org.apache.hadoop" % "hadoop-common" % "3.3.1",
		  "org.apache.spark" %% "spark-core"      % sparkVersion,
		  "org.apache.spark" %% "spark-sql"       % sparkVersion,
		  "net.sansa-stack" %% "sansa-rdf-spark" % sansaVersion,
		  "net.sansa-stack" %% "sansa-owl-spark" % sansaVersion,
		  "net.sansa-stack" %% "sansa-inference-spark" % sansaVersion,
		  "net.sansa-stack" %% "sansa-query-spark" % sansaVersion,
		  "net.sansa-stack" %% "sansa-ml-spark" % sansaVersion
    ),
    resolvers ++= Seq(
      "AKSW Maven Releases" at "https://maven.aksw.org/archiva/repository/internal",
      "AKSW Maven Snapshots" at "https://maven.aksw.org/archiva/repository/snapshots",
      "oss-sonatype" at "https://oss.sonatype.org/content/repositories/snapshots/",
      "Apache repository (snapshots)" at "https://repository.apache.org/content/repositories/snapshots/",
      "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/", "NetBeans" at "https://bits.netbeans.org/nexus/content/groups/netbeans/", "gephi" at "https://raw.github.com/gephi/gephi/mvn-thirdparty-repo/",
      Resolver.defaultLocal,
      Resolver.mavenLocal,
      "Local Maven Repository" at "file://"+Path.userHome.absolutePath+"/.m2/repository",
      "Apache Staging" at "https://repository.apache.org/content/repositories/staging/"
    )
  )

Global / onChangedBuildSource := ReloadOnSourceChanges
```

### stack stack
```shell
======================================
|        Triple reader example       |
======================================
[error] (run-main-0) java.lang.ExceptionInInitializerError
[error] java.lang.ExceptionInInitializerError
[error]         at org.apache.spark.SparkContext.withScope(SparkContext.scala:786)
[error]         at org.apache.spark.SparkContext.textFile(SparkContext.scala:917)
[error]         at net.sansa_stack.rdf.spark.io.NTripleReader$.loadLinesIntoRdd(NTripleReader.scala:92)
[error]         at net.sansa_stack.rdf.spark.io.NTripleReader$.load(NTripleReader.scala:156)
[error]         at net.sansa_stack.rdf.spark.io.package$RDFReader.$anonfun$ntriples$4(package.scala:423)
[error]         at net.sansa_stack.examples.spark.rdf.TripleReader$.run(TripleReader.scala:32)
[error]         at net.sansa_stack.examples.spark.rdf.TripleReader$.main(TripleReader.scala:13)
[error]         at net.sansa_stack.examples.spark.rdf.TripleReader.main(TripleReader.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.4 requires Jackson Databind version >= 2.10.0 and < 2.11.0
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error]         at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error]         at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
[error]         at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:82)
[error]         at org.apache.spark.rdd.RDDOperationScope$.<clinit>(RDDOperationScope.scala)
[error]         at org.apache.spark.SparkContext.withScope(SparkContext.scala:786)
[error]         at org.apache.spark.SparkContext.textFile(SparkContext.scala:917)
[error]         at net.sansa_stack.rdf.spark.io.NTripleReader$.loadLinesIntoRdd(NTripleReader.scala:92)
[error]         at net.sansa_stack.rdf.spark.io.NTripleReader$.load(NTripleReader.scala:156)
[error]         at net.sansa_stack.rdf.spark.io.package$RDFReader.$anonfun$ntriples$4(package.scala:423)
[error]         at net.sansa_stack.examples.spark.rdf.TripleReader$.run(TripleReader.scala:32)
[error]         at net.sansa_stack.examples.spark.rdf.TripleReader$.main(TripleReader.scala:13)
[error]         at net.sansa_stack.examples.spark.rdf.TripleReader.main(TripleReader.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 13 s, completed 9 Sep 2021, 12:55:39
```

Do you have any idea to solve this problem ?

**Comment by ofilangi** [comment]
sorry, this issue related to FasterXML : https://github.com/FasterXML/jackson-module-scala/issues/513
