### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by mjgm97** [SANSA-Stack/SANSA-Stack#180]
Hi!

I've been using Sansa-stack with java 15 (since it does not work with 16 and 17 versions), and it's working ok locally, but I'm trying to obtain the .jar with all the dependencies with "mvn clean package", and then I got an error in sansa-rdf-common_2.12. Specifically, I'm getting :

```
- export partition as R2RML should work *** FAILED ***
  org.apache.jena.enhanced.UnsupportedPolymorphismException: cannot convert a4e8acd1-5c3e-4534-9556-a4d81a875bd0 to interface org.aksw.r2rml.jena.domain.api.TriplesMap
  at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:158)
  at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:31)
  at org.apache.jena.enhanced.Polymorphic.asInternal(Polymorphic.java:62)
  at org.apache.jena.enhanced.EnhNode.as(EnhNode.java:114)
  at net.sansa_stack.rdf.common.partition.r2rml.R2rmlUtils$.createR2rmlMappings(R2rmlUtils.scala:203)
  at net.sansa_stack.rdf.common.partition.r2rml.R2rmlUtils$.createR2rmlMappings(R2rmlUtils.scala:113)
  at net.sansa_stack.rdf.common.partition.core.RdfPartitionerDefaultTests.$anonfun$new$6(RdfPartitionerDefaultTests.scala:74)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

*** 3 TESTS FAILED ***
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for sansa-rdf-common_2.12 0.8.0-RC2-SNAPSHOT:
[INFO] 
[INFO] sansa-rdf-common_2.12 .............................. FAILURE [ 14.225 s]
[INFO] sansa-rdf-spark_2.12 ............................... SKIPPED
[INFO] SANSA Stack - DataLake Layer - Parent .............. SKIPPED
[INFO] sansa-datalake-spark_2.12 .......................... SKIPPED
[INFO] SANSA Stack - Query Layer - Parent ................. SKIPPED
[INFO] sansa-query-common_2.12 ............................ SKIPPED
[INFO] sansa-query-tests_2.12 ............................. SKIPPED
[INFO] sansa-query-spark_2.12 ............................. SKIPPED
[INFO] OWL - Parent ....................................... SKIPPED
[INFO] SANSA OWL layer - Common ........................... SKIPPED
[INFO] SANSA OWL layer - SPARK ............................ SKIPPED
[INFO] Inference API - Parent ............................. SKIPPED
[INFO] Inference API - Common ............................. SKIPPED
[INFO] Inference API - Tests .............................. SKIPPED
[INFO] Inference API - Spark .............................. SKIPPED
[INFO] ML API - Parent .................................... SKIPPED
[INFO] ML API - Common .................................... SKIPPED
[INFO] ML API - Apache Spark .............................. SKIPPED
[INFO] SANSA-Examples - Parent ............................ SKIPPED
[INFO] SANSA Examples - Apache Spark ...................... SKIPPED
[INFO] SANSA Stack - Integration Tests .................... SKIPPED
[INFO] sansa-spark-cli_2.12 ............................... SKIPPED
[INFO] sansa-debian-spark-cli ............................. SKIPPED
[INFO] sansa-bench-spark_2.12 ............................. SKIPPED
[INFO] sansa-stack_2.12 ................................... SKIPPED
[INFO] SANSA Stack - Spark ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.358 s
[INFO] Finished at: 2022-02-02T18:20:55+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:2.0.2:test (test) on project sansa-rdf-common_2.12: There are test failures -> [Help 1]
```

I don't know if it could be some error with library or java versions, any idea? 

Thanks!

**Comment by mjgm97** [comment]
A little update: it stopped working also locally, this is the full exception trace:

```
Exception in thread "main" org.apache.jena.enhanced.UnsupportedPolymorphismException: cannot convert dd3a0916-6eaf-46b8-943e-084c06477113 to interface org.aksw.r2rml.jena.domain.api.TriplesMap
	at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:158)
	at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:31)
	at org.apache.jena.enhanced.Polymorphic.asInternal(Polymorphic.java:62)
	at org.apache.jena.enhanced.EnhNode.as(EnhNode.java:114)
	at net.sansa_stack.rdf.common.partition.r2rml.R2rmlUtils$.createR2rmlMappings(R2rmlUtils.scala:203)
	at net.sansa_stack.rdf.common.partition.r2rml.R2rmlUtils$.$anonfun$createR2rmlMappings$2(R2rmlUtils.scala:85)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:280)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:280)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:277)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at net.sansa_stack.rdf.common.partition.r2rml.R2rmlUtils$.createR2rmlMappings(R2rmlUtils.scala:78)
	at net.sansa_stack.rdf.spark.partition.package$RDFPartition.verticalPartition(package.scala:77)
	at net.sansa_stack.query.spark.api.impl.QueryEngineFactoryBase.createWithPartitioning(QueryEngineFactoryBase.scala:35)
	at net.sansa_stack.query.spark.ontop.QueryEngineFactoryOntop.createWithPartitioning(QueryEngineFactoryOntop.scala:30)
	at net.sansa_stack.query.spark.api.impl.QueryEngineFactoryBase.create(QueryEngineFactoryBase.scala:42)
	at net.sansa_stack.examples.spark.query.SPARQLExample$.main(SPARQLExample.scala:84)
	at net.sansa_stack.examples.spark.query.SPARQLExample.main(SPARQLExample.scala)

```

**Comment by Aklakan** [comment]
Hi, the issue was due to moved classes in one of the snapshot dependencies and should be fixed. I am leaving this issue open for reference until the stable release is complete because fixing broken tests in those deps may still cause temporary regressions in Sansa/develop branch :/
