### ISSUE TITLE
Datatype parsing of DataFrame Row Triple parser in net.sansa_stack.rdf.spark.io seems to be wrong

### ISSUE THREAD

**Issue by patrickwestphal** [SANSA-Stack/SANSA-Stack#99]
`net.sansa_stack.rdf.spark.io.fromRow` is a function that, given a `Row` object, tries to generate `Triple` objects by parsing the subject, predicate and objects parts of its string representation. For the case of a typed literal on object position the [following code snippet](https://github.com/SANSA-Stack/SANSA-RDF/blob/develop/sansa-rdf-spark/src/main/scala/net/sansa_stack/rdf/spark/io/package.scala#L94-L100) is executed:

```scala
var lit = oStr  // the raw string representation
val idx = oStr.indexOf("^^")
if (idx > 0) {
  val first = oStr.substring(0, idx)
  val second = "<" + oStr.substring(idx + 2).trim + ">"
  lit = first + "^^" + second
}
NodeFactoryExtra.parseNode(lit)
```

In line 5 angle brackets are added which is not needed as the string representation of the datatype already contains angle brackets. As a consequence the parsing of a datatype fails in the last line:

```
org.apache.jena.riot.RiotParseException: [line: 1, col: 17] Bad character in IRI (bad character: '<'): <[<]...>
	at org.apache.jena.riot.tokens.TokenizerText$ErrorHandlerTokenizer.error(TokenizerText.java:65)
	at org.apache.jena.riot.tokens.TokenizerText.error(TokenizerText.java:1244)
	at org.apache.jena.riot.tokens.TokenizerText.readIRI(TokenizerText.java:484)
	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:204)
	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:277)
	at org.apache.jena.riot.tokens.TokenizerText.hasNext(TokenizerText.java:99)
	at org.apache.jena.sparql.util.NodeFactoryExtra.parseNode(NodeFactoryExtra.java:73)
	at org.apache.jena.sparql.util.NodeFactoryExtra.parseNode(NodeFactoryExtra.java:55)
	at net.sansa_stack.rdf.spark.io.package$.fromRow(package.scala:101)
        ...
```

**Comment by LorenzBuehmann** [comment]
Has been fixed, `toRow` and `fromRow` are now inverse operations on a `s,p,o` Dataframe
